version: '3'
services:
  node-app:
    build: .
    image: node-app
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db

volumes:
  mongo-db:
